<?php

return [
    'countries' => [
        ['code' => 'ID', 'dial' => '+62', 'name' => 'Indonesia', 'flag' => '🇮🇩'],
        ['code' => 'AF', 'dial' => '+93', 'name' => 'Afghanistan', 'flag' => '🇦🇫'],
        ['code' => 'AX', 'dial' => '+358', 'name' => 'Aland Islands', 'flag' => '🇦🇽'],
        ['code' => 'AL', 'dial' => '+355', 'name' => 'Albania', 'flag' => '🇦🇱'],
        ['code' => 'DZ', 'dial' => '+213', 'name' => 'Algeria', 'flag' => '🇩🇿'],
        ['code' => 'AS', 'dial' => '+1684', 'name' => 'AmericanSamoa', 'flag' => '🇦🇸'],
        ['code' => 'AD', 'dial' => '+376', 'name' => 'Andorra', 'flag' => '🇦🇩'],
        ['code' => 'AO', 'dial' => '+244', 'name' => 'Angola', 'flag' => '🇦🇴'],
        ['code' => 'AI', 'dial' => '+1264', 'name' => 'Anguilla', 'flag' => '🇦🇮'],
        ['code' => 'AQ', 'dial' => '+672', 'name' => 'Antarctica', 'flag' => '🇦🇶'],
        ['code' => 'AG', 'dial' => '+1268', 'name' => 'Antigua and Barbuda', 'flag' => '🇦🇬'],
        ['code' => 'AR', 'dial' => '+54', 'name' => 'Argentina', 'flag' => '🇦🇷'],
        ['code' => 'AM', 'dial' => '+374', 'name' => 'Armenia', 'flag' => '🇦🇲'],
        ['code' => 'AW', 'dial' => '+297', 'name' => 'Aruba', 'flag' => '🇦🇼'],
        ['code' => 'AU', 'dial' => '+61', 'name' => 'Australia', 'flag' => '🇦🇺'],
        ['code' => 'AT', 'dial' => '+43', 'name' => 'Austria', 'flag' => '🇦🇹'],
        ['code' => 'AZ', 'dial' => '+994', 'name' => 'Azerbaijan', 'flag' => '🇦🇿'],
        ['code' => 'BS', 'dial' => '+1242', 'name' => 'Bahamas', 'flag' => '🇧🇸'],
        ['code' => 'BH', 'dial' => '+973', 'name' => 'Bahrain', 'flag' => '🇧🇭'],
        ['code' => 'BD', 'dial' => '+880', 'name' => 'Bangladesh', 'flag' => '🇧🇩'],
        ['code' => 'BB', 'dial' => '+1246', 'name' => 'Barbados', 'flag' => '🇧🇧'],
        ['code' => 'BY', 'dial' => '+375', 'name' => 'Belarus', 'flag' => '🇧🇾'],
        ['code' => 'BE', 'dial' => '+32', 'name' => 'Belgium', 'flag' => '🇧🇪'],
        ['code' => 'BZ', 'dial' => '+501', 'name' => 'Belize', 'flag' => '🇧🇿'],
        ['code' => 'BJ', 'dial' => '+229', 'name' => 'Benin', 'flag' => '🇧🇯'],
        ['code' => 'BM', 'dial' => '+1441', 'name' => 'Bermuda', 'flag' => '🇧🇲'],
        ['code' => 'BT', 'dial' => '+975', 'name' => 'Bhutan', 'flag' => '🇧🇹'],
        ['code' => 'BO', 'dial' => '+591', 'name' => 'Bolivia, Plurinational State of', 'flag' => '🇧🇴'],
        ['code' => 'BA', 'dial' => '+387', 'name' => 'Bosnia and Herzegovina', 'flag' => '🇧🇦'],
        ['code' => 'BW', 'dial' => '+267', 'name' => 'Botswana', 'flag' => '🇧🇼'],
        ['code' => 'BR', 'dial' => '+55', 'name' => 'Brazil', 'flag' => '🇧🇷'],
        ['code' => 'IO', 'dial' => '+246', 'name' => 'British Indian Ocean Territory', 'flag' => '🇮🇴'],
        ['code' => 'BN', 'dial' => '+673', 'name' => 'Brunei Darussalam', 'flag' => '🇧🇳'],
        ['code' => 'BG', 'dial' => '+359', 'name' => 'Bulgaria', 'flag' => '🇧🇬'],
        ['code' => 'BF', 'dial' => '+226', 'name' => 'Burkina Faso', 'flag' => '🇧🇫'],
        ['code' => 'BI', 'dial' => '+257', 'name' => 'Burundi', 'flag' => '🇧🇮'],
        ['code' => 'KH', 'dial' => '+855', 'name' => 'Cambodia', 'flag' => '🇰🇭'],
        ['code' => 'CM', 'dial' => '+237', 'name' => 'Cameroon', 'flag' => '🇨🇲'],
        ['code' => 'CA', 'dial' => '+1', 'name' => 'Canada', 'flag' => '🇨🇦'],
        ['code' => 'CV', 'dial' => '+238', 'name' => 'Cape Verde', 'flag' => '🇨🇻'],
        ['code' => 'KY', 'dial' => '+345', 'name' => 'Cayman Islands', 'flag' => '🇰🇾'],
        ['code' => 'CF', 'dial' => '+236', 'name' => 'Central African Republic', 'flag' => '🇨🇫'],
        ['code' => 'TD', 'dial' => '+235', 'name' => 'Chad', 'flag' => '🇹🇩'],
        ['code' => 'CL', 'dial' => '+56', 'name' => 'Chile', 'flag' => '🇨🇱'],
        ['code' => 'CN', 'dial' => '+86', 'name' => 'China', 'flag' => '🇨🇳'],
        ['code' => 'CX', 'dial' => '+61', 'name' => 'Christmas Island', 'flag' => '🇨🇽'],
        ['code' => 'CC', 'dial' => '+61', 'name' => 'Cocos (Keeling) Islands', 'flag' => '🇨🇨'],
        ['code' => 'CO', 'dial' => '+57', 'name' => 'Colombia', 'flag' => '🇨🇴'],
        ['code' => 'KM', 'dial' => '+269', 'name' => 'Comoros', 'flag' => '🇰🇲'],
        ['code' => 'CG', 'dial' => '+242', 'name' => 'Congo', 'flag' => '🇨🇬'],
        ['code' => 'CD', 'dial' => '+243', 'name' => 'Congo, The Democratic Republic of the Congo', 'flag' => '🇨🇩'],
        ['code' => 'CK', 'dial' => '+682', 'name' => 'Cook Islands', 'flag' => '🇨🇰'],
        ['code' => 'CR', 'dial' => '+506', 'name' => 'Costa Rica', 'flag' => '🇨🇷'],
        ['code' => 'CI', 'dial' => '+225', 'name' => 'Cote d\'Ivoire', 'flag' => '🇨🇮'],
        ['code' => 'HR', 'dial' => '+385', 'name' => 'Croatia', 'flag' => '🇭🇷'],
        ['code' => 'CU', 'dial' => '+53', 'name' => 'Cuba', 'flag' => '🇨🇺'],
        ['code' => 'CY', 'dial' => '+357', 'name' => 'Cyprus', 'flag' => '🇨🇾'],
        ['code' => 'CZ', 'dial' => '+420', 'name' => 'Czech Republic', 'flag' => '🇨🇿'],
        ['code' => 'DK', 'dial' => '+45', 'name' => 'Denmark', 'flag' => '🇩🇰'],
        ['code' => 'DJ', 'dial' => '+253', 'name' => 'Djibouti', 'flag' => '🇩🇯'],
        ['code' => 'DM', 'dial' => '+1767', 'name' => 'Dominica', 'flag' => '🇩🇲'],
        ['code' => 'DO', 'dial' => '+1849', 'name' => 'Dominican Republic', 'flag' => '🇩🇴'],
        ['code' => 'EC', 'dial' => '+593', 'name' => 'Ecuador', 'flag' => '🇪🇨'],
        ['code' => 'EG', 'dial' => '+20', 'name' => 'Egypt', 'flag' => '🇪🇬'],
        ['code' => 'SV', 'dial' => '+503', 'name' => 'El Salvador', 'flag' => '🇸🇻'],
        ['code' => 'GQ', 'dial' => '+240', 'name' => 'Equatorial Guinea', 'flag' => '🇬🇶'],
        ['code' => 'ER', 'dial' => '+291', 'name' => 'Eritrea', 'flag' => '🇪🇷'],
        ['code' => 'EE', 'dial' => '+372', 'name' => 'Estonia', 'flag' => '🇪🇪'],
        ['code' => 'ET', 'dial' => '+251', 'name' => 'Ethiopia', 'flag' => '🇪🇹'],
        ['code' => 'FK', 'dial' => '+500', 'name' => 'Falkland Islands (Malvinas)', 'flag' => '🇫🇰'],
        ['code' => 'FO', 'dial' => '+298', 'name' => 'Faroe Islands', 'flag' => '🇫🇴'],
        ['code' => 'FJ', 'dial' => '+679', 'name' => 'Fiji', 'flag' => '🇫🇯'],
        ['code' => 'FI', 'dial' => '+358', 'name' => 'Finland', 'flag' => '🇫🇮'],
        ['code' => 'FR', 'dial' => '+33', 'name' => 'France', 'flag' => '🇫🇷'],
        ['code' => 'GF', 'dial' => '+594', 'name' => 'French Guiana', 'flag' => '🇬🇫'],
        ['code' => 'PF', 'dial' => '+689', 'name' => 'French Polynesia', 'flag' => '🇵🇫'],
        ['code' => 'GA', 'dial' => '+241', 'name' => 'Gabon', 'flag' => '🇬🇦'],
        ['code' => 'GM', 'dial' => '+220', 'name' => 'Gambia', 'flag' => '🇬🇲'],
        ['code' => 'GE', 'dial' => '+995', 'name' => 'Georgia', 'flag' => '🇬🇪'],
        ['code' => 'DE', 'dial' => '+49', 'name' => 'Germany', 'flag' => '🇩🇪'],
        ['code' => 'GH', 'dial' => '+233', 'name' => 'Ghana', 'flag' => '🇬🇭'],
        ['code' => 'GI', 'dial' => '+350', 'name' => 'Gibraltar', 'flag' => '🇬🇮'],
        ['code' => 'GR', 'dial' => '+30', 'name' => 'Greece', 'flag' => '🇬🇷'],
        ['code' => 'GL', 'dial' => '+299', 'name' => 'Greenland', 'flag' => '🇬🇱'],
        ['code' => 'GD', 'dial' => '+1473', 'name' => 'Grenada', 'flag' => '🇬🇩'],
        ['code' => 'GP', 'dial' => '+590', 'name' => 'Guadeloupe', 'flag' => '🇬🇵'],
        ['code' => 'GU', 'dial' => '+1671', 'name' => 'Guam', 'flag' => '🇬🇺'],
        ['code' => 'GT', 'dial' => '+502', 'name' => 'Guatemala', 'flag' => '🇬🇹'],
        ['code' => 'GG', 'dial' => '+44', 'name' => 'Guernsey', 'flag' => '🇬🇬'],
        ['code' => 'GN', 'dial' => '+224', 'name' => 'Guinea', 'flag' => '🇬🇳'],
        ['code' => 'GW', 'dial' => '+245', 'name' => 'Guinea-Bissau', 'flag' => '🇬🇼'],
        ['code' => 'GY', 'dial' => '+595', 'name' => 'Guyana', 'flag' => '🇬🇾'],
        ['code' => 'HT', 'dial' => '+509', 'name' => 'Haiti', 'flag' => '🇭🇹'],
        ['code' => 'VA', 'dial' => '+379', 'name' => 'Holy See (Vatican City State)', 'flag' => '🇻🇦'],
        ['code' => 'HN', 'dial' => '+504', 'name' => 'Honduras', 'flag' => '🇭🇳'],
        ['code' => 'HK', 'dial' => '+852', 'name' => 'Hong Kong', 'flag' => '🇭🇰'],
        ['code' => 'HU', 'dial' => '+36', 'name' => 'Hungary', 'flag' => '🇭🇺'],
        ['code' => 'IS', 'dial' => '+354', 'name' => 'Iceland', 'flag' => '🇮🇸'],
        ['code' => 'IN', 'dial' => '+91', 'name' => 'India', 'flag' => '🇮🇳'],
        ['code' => 'IR', 'dial' => '+98', 'name' => 'Iran, Islamic Republic of Persian Gulf', 'flag' => '🇮🇷'],
        ['code' => 'IQ', 'dial' => '+964', 'name' => 'Iraq', 'flag' => '🇮🇶'],
        ['code' => 'IE', 'dial' => '+353', 'name' => 'Ireland', 'flag' => '🇮🇪'],
        ['code' => 'IM', 'dial' => '+44', 'name' => 'Isle of Man', 'flag' => '🇮🇲'],
        ['code' => 'IL', 'dial' => '+972', 'name' => 'Israel', 'flag' => '🇮🇱'],
        ['code' => 'IT', 'dial' => '+39', 'name' => 'Italy', 'flag' => '🇮🇹'],
        ['code' => 'JM', 'dial' => '+1876', 'name' => 'Jamaica', 'flag' => '🇯🇲'],
        ['code' => 'JP', 'dial' => '+81', 'name' => 'Japan', 'flag' => '🇯🇵'],
        ['code' => 'JE', 'dial' => '+44', 'name' => 'Jersey', 'flag' => '🇯🇪'],
        ['code' => 'JO', 'dial' => '+962', 'name' => 'Jordan', 'flag' => '🇯🇴'],
        ['code' => 'KZ', 'dial' => '+77', 'name' => 'Kazakhstan', 'flag' => '🇰🇿'],
        ['code' => 'KE', 'dial' => '+254', 'name' => 'Kenya', 'flag' => '🇰🇪'],
        ['code' => 'KI', 'dial' => '+686', 'name' => 'Kiribati', 'flag' => '🇰🇮'],
        ['code' => 'KP', 'dial' => '+850', 'name' => 'Korea, Democratic People\'s Republic of Korea', 'flag' => '🇰🇵'],
        ['code' => 'KR', 'dial' => '+82', 'name' => 'Korea, Republic of South Korea', 'flag' => '🇰🇷'],
        ['code' => 'KW', 'dial' => '+965', 'name' => 'Kuwait', 'flag' => '🇰🇼'],
        ['code' => 'KG', 'dial' => '+996', 'name' => 'Kyrgyzstan', 'flag' => '🇰🇬'],
        ['code' => 'LA', 'dial' => '+856', 'name' => 'Laos', 'flag' => '🇱🇦'],
        ['code' => 'LV', 'dial' => '+371', 'name' => 'Latvia', 'flag' => '🇱🇻'],
        ['code' => 'LB', 'dial' => '+961', 'name' => 'Lebanon', 'flag' => '🇱🇧'],
        ['code' => 'LS', 'dial' => '+266', 'name' => 'Lesotho', 'flag' => '🇱🇸'],
        ['code' => 'LR', 'dial' => '+231', 'name' => 'Liberia', 'flag' => '🇱🇷'],
        ['code' => 'LY', 'dial' => '+218', 'name' => 'Libyan Arab Jamahiriya', 'flag' => '🇱🇾'],
        ['code' => 'LI', 'dial' => '+423', 'name' => 'Liechtenstein', 'flag' => '🇱🇮'],
        ['code' => 'LT', 'dial' => '+370', 'name' => 'Lithuania', 'flag' => '🇱🇹'],
        ['code' => 'LU', 'dial' => '+352', 'name' => 'Luxembourg', 'flag' => '🇱🇺'],
        ['code' => 'MO', 'dial' => '+853', 'name' => 'Macao', 'flag' => '🇲🇴'],
        ['code' => 'MK', 'dial' => '+389', 'name' => 'Macedonia', 'flag' => '🇲🇰'],
        ['code' => 'MG', 'dial' => '+261', 'name' => 'Madagascar', 'flag' => '🇲🇬'],
        ['code' => 'MW', 'dial' => '+265', 'name' => 'Malawi', 'flag' => '🇲🇼'],
        ['code' => 'MY', 'dial' => '+60', 'name' => 'Malaysia', 'flag' => '🇲🇾'],
        ['code' => 'MV', 'dial' => '+960', 'name' => 'Maldives', 'flag' => '🇲🇻'],
        ['code' => 'ML', 'dial' => '+223', 'name' => 'Mali', 'flag' => '🇲🇱'],
        ['code' => 'MT', 'dial' => '+356', 'name' => 'Malta', 'flag' => '🇲🇹'],
        ['code' => 'MH', 'dial' => '+692', 'name' => 'Marshall Islands', 'flag' => '🇲🇭'],
        ['code' => 'MQ', 'dial' => '+596', 'name' => 'Martinique', 'flag' => '🇲🇶'],
        ['code' => 'MR', 'dial' => '+222', 'name' => 'Mauritania', 'flag' => '🇲🇷'],
        ['code' => 'MU', 'dial' => '+230', 'name' => 'Mauritius', 'flag' => '🇲🇺'],
        ['code' => 'YT', 'dial' => '+262', 'name' => 'Mayotte', 'flag' => '🇾🇹'],
        ['code' => 'MX', 'dial' => '+52', 'name' => 'Mexico', 'flag' => '🇲🇽'],
        ['code' => 'FM', 'dial' => '+691', 'name' => 'Micronesia, Federated States of Micronesia', 'flag' => '🇫🇲'],
        ['code' => 'MD', 'dial' => '+373', 'name' => 'Moldova', 'flag' => '🇲🇩'],
        ['code' => 'MC', 'dial' => '+377', 'name' => 'Monaco', 'flag' => '🇲🇨'],
        ['code' => 'MN', 'dial' => '+976', 'name' => 'Mongolia', 'flag' => '🇲🇳'],
        ['code' => 'ME', 'dial' => '+382', 'name' => 'Montenegro', 'flag' => '🇲🇪'],
        ['code' => 'MS', 'dial' => '+1664', 'name' => 'Montserrat', 'flag' => '🇲🇸'],
        ['code' => 'MA', 'dial' => '+212', 'name' => 'Morocco', 'flag' => '🇲🇦'],
        ['code' => 'MZ', 'dial' => '+258', 'name' => 'Mozambique', 'flag' => '🇲🇿'],
        ['code' => 'MM', 'dial' => '+95', 'name' => 'Myanmar', 'flag' => '🇲🇲'],
        ['code' => 'NA', 'dial' => '+264', 'name' => 'Namibia', 'flag' => '🇳🇦'],
        ['code' => 'NR', 'dial' => '+674', 'name' => 'Nauru', 'flag' => '🇳🇷'],
        ['code' => 'NP', 'dial' => '+977', 'name' => 'Nepal', 'flag' => '🇳🇵'],
        ['code' => 'NL', 'dial' => '+31', 'name' => 'Netherlands', 'flag' => '🇳🇱'],
        ['code' => 'AN', 'dial' => '+599', 'name' => 'Netherlands Antilles', 'flag' => '🇦🇳'],
        ['code' => 'NC', 'dial' => '+687', 'name' => 'New Caledonia', 'flag' => '🇳🇨'],
        ['code' => 'NZ', 'dial' => '+64', 'name' => 'New Zealand', 'flag' => '🇳🇿'],
        ['code' => 'NI', 'dial' => '+505', 'name' => 'Nicaragua', 'flag' => '🇳🇮'],
        ['code' => 'NE', 'dial' => '+227', 'name' => 'Niger', 'flag' => '🇳🇪'],
        ['code' => 'NG', 'dial' => '+234', 'name' => 'Nigeria', 'flag' => '🇳🇬'],
        ['code' => 'NU', 'dial' => '+683', 'name' => 'Niue', 'flag' => '🇳🇺'],
        ['code' => 'NF', 'dial' => '+672', 'name' => 'Norfolk Island', 'flag' => '🇳🇫'],
        ['code' => 'MP', 'dial' => '+1670', 'name' => 'Northern Mariana Islands', 'flag' => '🇲🇵'],
        ['code' => 'NO', 'dial' => '+47', 'name' => 'Norway', 'flag' => '🇳🇴'],
        ['code' => 'OM', 'dial' => '+968', 'name' => 'Oman', 'flag' => '🇴🇲'],
        ['code' => 'PK', 'dial' => '+92', 'name' => 'Pakistan', 'flag' => '🇵🇰'],
        ['code' => 'PW', 'dial' => '+680', 'name' => 'Palau', 'flag' => '🇵🇼'],
        ['code' => 'PS', 'dial' => '+970', 'name' => 'Palestinian Territory, Occupied', 'flag' => '🇵🇸'],
        ['code' => 'PA', 'dial' => '+507', 'name' => 'Panama', 'flag' => '🇵🇦'],
        ['code' => 'PG', 'dial' => '+675', 'name' => 'Papua New Guinea', 'flag' => '🇵🇬'],
        ['code' => 'PY', 'dial' => '+595', 'name' => 'Paraguay', 'flag' => '🇵🇾'],
        ['code' => 'PE', 'dial' => '+51', 'name' => 'Peru', 'flag' => '🇵🇪'],
        ['code' => 'PH', 'dial' => '+63', 'name' => 'Philippines', 'flag' => '🇵🇭'],
        ['code' => 'PN', 'dial' => '+872', 'name' => 'Pitcairn', 'flag' => '🇵🇳'],
        ['code' => 'PL', 'dial' => '+48', 'name' => 'Poland', 'flag' => '🇵🇱'],
        ['code' => 'PT', 'dial' => '+351', 'name' => 'Portugal', 'flag' => '🇵🇹'],
        ['code' => 'PR', 'dial' => '+1939', 'name' => 'Puerto Rico', 'flag' => '🇵🇷'],
        ['code' => 'QA', 'dial' => '+974', 'name' => 'Qatar', 'flag' => '🇶🇦'],
        ['code' => 'RE', 'dial' => '+262', 'name' => 'Reunion', 'flag' => '🇷🇪'],
        ['code' => 'RO', 'dial' => '+40', 'name' => 'Romania', 'flag' => '🇷🇴'],
        ['code' => 'RU', 'dial' => '+7', 'name' => 'Russia', 'flag' => '🇷🇺'],
        ['code' => 'RW', 'dial' => '+250', 'name' => 'Rwanda', 'flag' => '🇷🇼'],
        ['code' => 'BL', 'dial' => '+590', 'name' => 'Saint Barthelemy', 'flag' => '🇧🇱'],
        ['code' => 'SH', 'dial' => '+290', 'name' => 'Saint Helena, Ascension and Tristan Da Cunha', 'flag' => '🇸🇭'],
        ['code' => 'KN', 'dial' => '+1869', 'name' => 'Saint Kitts and Nevis', 'flag' => '🇰🇳'],
        ['code' => 'LC', 'dial' => '+1758', 'name' => 'Saint Lucia', 'flag' => '🇱🇨'],
        ['code' => 'MF', 'dial' => '+590', 'name' => 'Saint Martin', 'flag' => '🇲🇫'],
        ['code' => 'PM', 'dial' => '+508', 'name' => 'Saint Pierre and Miquelon', 'flag' => '🇵🇲'],
        ['code' => 'VC', 'dial' => '+1784', 'name' => 'Saint Vincent and the Grenadines', 'flag' => '🇻🇨'],
        ['code' => 'WS', 'dial' => '+685', 'name' => 'Samoa', 'flag' => '🇼🇸'],
        ['code' => 'SM', 'dial' => '+378', 'name' => 'San Marino', 'flag' => '🇸🇲'],
        ['code' => 'ST', 'dial' => '+239', 'name' => 'Sao Tome and Principe', 'flag' => '🇸🇹'],
        ['code' => 'SA', 'dial' => '+966', 'name' => 'Saudi Arabia', 'flag' => '🇸🇦'],
        ['code' => 'SN', 'dial' => '+221', 'name' => 'Senegal', 'flag' => '🇸🇳'],
        ['code' => 'RS', 'dial' => '+381', 'name' => 'Serbia', 'flag' => '🇷🇸'],
        ['code' => 'SC', 'dial' => '+248', 'name' => 'Seychelles', 'flag' => '🇸🇨'],
        ['code' => 'SL', 'dial' => '+232', 'name' => 'Sierra Leone', 'flag' => '🇸🇱'],
        ['code' => 'SG', 'dial' => '+65', 'name' => 'Singapore', 'flag' => '🇸🇬'],
        ['code' => 'SK', 'dial' => '+421', 'name' => 'Slovakia', 'flag' => '🇸🇰'],
        ['code' => 'SI', 'dial' => '+386', 'name' => 'Slovenia', 'flag' => '🇸🇮'],
        ['code' => 'SB', 'dial' => '+677', 'name' => 'Solomon Islands', 'flag' => '🇸🇧'],
        ['code' => 'SO', 'dial' => '+252', 'name' => 'Somalia', 'flag' => '🇸🇴'],
        ['code' => 'ZA', 'dial' => '+27', 'name' => 'South Africa', 'flag' => '🇿🇦'],
        ['code' => 'GS', 'dial' => '+500', 'name' => 'South Georgia and the South Sandwich Islands', 'flag' => '🇬🇸'],
        ['code' => 'SS', 'dial' => '+211', 'name' => 'South Sudan', 'flag' => '🇸🇸'],
        ['code' => 'ES', 'dial' => '+34', 'name' => 'Spain', 'flag' => '🇪🇸'],
        ['code' => 'LK', 'dial' => '+94', 'name' => 'Sri Lanka', 'flag' => '🇱🇰'],
        ['code' => 'SD', 'dial' => '+249', 'name' => 'Sudan', 'flag' => '🇸🇩'],
        ['code' => 'SR', 'dial' => '+597', 'name' => 'Suriname', 'flag' => '🇸🇷'],
        ['code' => 'SJ', 'dial' => '+47', 'name' => 'Svalbard and Jan Mayen', 'flag' => '🇸🇯'],
        ['code' => 'SZ', 'dial' => '+268', 'name' => 'Swaziland', 'flag' => '🇸🇿'],
        ['code' => 'SE', 'dial' => '+46', 'name' => 'Sweden', 'flag' => '🇸🇪'],
        ['code' => 'CH', 'dial' => '+41', 'name' => 'Switzerland', 'flag' => '🇨🇭'],
        ['code' => 'SY', 'dial' => '+963', 'name' => 'Syrian Arab Republic', 'flag' => '🇸🇾'],
        ['code' => 'TW', 'dial' => '+886', 'name' => 'Taiwan', 'flag' => '🇹🇼'],
        ['code' => 'TJ', 'dial' => '+992', 'name' => 'Tajikistan', 'flag' => '🇹🇯'],
        ['code' => 'TZ', 'dial' => '+255', 'name' => 'Tanzania, United Republic of Tanzania', 'flag' => '🇹🇿'],
        ['code' => 'TH', 'dial' => '+66', 'name' => 'Thailand', 'flag' => '🇹🇭'],
        ['code' => 'TL', 'dial' => '+670', 'name' => 'Timor-Leste', 'flag' => '🇹🇱'],
        ['code' => 'TG', 'dial' => '+228', 'name' => 'Togo', 'flag' => '🇹🇬'],
        ['code' => 'TK', 'dial' => '+690', 'name' => 'Tokelau', 'flag' => '🇹🇰'],
        ['code' => 'TO', 'dial' => '+676', 'name' => 'Tonga', 'flag' => '🇹🇴'],
        ['code' => 'TT', 'dial' => '+1868', 'name' => 'Trinidad and Tobago', 'flag' => '🇹🇹'],
        ['code' => 'TN', 'dial' => '+216', 'name' => 'Tunisia', 'flag' => '🇹🇳'],
        ['code' => 'TR', 'dial' => '+90', 'name' => 'Turkey', 'flag' => '🇹🇷'],
        ['code' => 'TM', 'dial' => '+993', 'name' => 'Turkmenistan', 'flag' => '🇹🇲'],
        ['code' => 'TC', 'dial' => '+1649', 'name' => 'Turks and Caicos Islands', 'flag' => '🇹🇨'],
        ['code' => 'TV', 'dial' => '+688', 'name' => 'Tuvalu', 'flag' => '🇹🇻'],
        ['code' => 'UG', 'dial' => '+256', 'name' => 'Uganda', 'flag' => '🇺🇬'],
        ['code' => 'UA', 'dial' => '+380', 'name' => 'Ukraine', 'flag' => '🇺🇦'],
        ['code' => 'AE', 'dial' => '+971', 'name' => 'United Arab Emirates', 'flag' => '🇦🇪'],
        ['code' => 'GB', 'dial' => '+44', 'name' => 'United Kingdom', 'flag' => '🇬🇧'],
        ['code' => 'US', 'dial' => '+1', 'name' => 'United States', 'flag' => '🇺🇸'],
        ['code' => 'UY', 'dial' => '+598', 'name' => 'Uruguay', 'flag' => '🇺🇾'],
        ['code' => 'UZ', 'dial' => '+998', 'name' => 'Uzbekistan', 'flag' => '🇺🇿'],
        ['code' => 'VU', 'dial' => '+678', 'name' => 'Vanuatu', 'flag' => '🇻🇺'],
        ['code' => 'VE', 'dial' => '+58', 'name' => 'Venezuela, Bolivarian Republic of Venezuela', 'flag' => '🇻🇪'],
        ['code' => 'VN', 'dial' => '+84', 'name' => 'Vietnam', 'flag' => '🇻🇳'],
        ['code' => 'VG', 'dial' => '+1284', 'name' => 'Virgin Islands, British', 'flag' => '🇻🇬'],
        ['code' => 'VI', 'dial' => '+1340', 'name' => 'Virgin Islands, U.S.', 'flag' => '🇻🇮'],
        ['code' => 'WF', 'dial' => '+681', 'name' => 'Wallis and Futuna', 'flag' => '🇼🇫'],
        ['code' => 'YE', 'dial' => '+967', 'name' => 'Yemen', 'flag' => '🇾🇪'],
        ['code' => 'ZM', 'dial' => '+260', 'name' => 'Zambia', 'flag' => '🇿🇲'],
        ['code' => 'ZW', 'dial' => '+263', 'name' => 'Zimbabwe', 'flag' => '🇿🇼'],
    ],

    'prefixes' => [
        '+1684',
        '+1264',
        '+1268',
        '+1242',
        '+1246',
        '+1441',
        '+1767',
        '+1849',
        '+1473',
        '+1671',
        '+1876',
        '+1664',
        '+1670',
        '+1939',
        '+1869',
        '+1758',
        '+1784',
        '+1868',
        '+1649',
        '+1284',
        '+1340',
        '+358',
        '+355',
        '+213',
        '+376',
        '+244',
        '+672',
        '+374',
        '+297',
        '+994',
        '+973',
        '+880',
        '+375',
        '+501',
        '+229',
        '+975',
        '+591',
        '+387',
        '+267',
        '+246',
        '+673',
        '+359',
        '+226',
        '+257',
        '+855',
        '+237',
        '+238',
        '+345',
        '+236',
        '+235',
        '+269',
        '+242',
        '+243',
        '+682',
        '+506',
        '+225',
        '+385',
        '+357',
        '+420',
        '+253',
        '+593',
        '+503',
        '+240',
        '+291',
        '+372',
        '+251',
        '+500',
        '+298',
        '+679',
        '+594',
        '+689',
        '+241',
        '+220',
        '+995',
        '+233',
        '+350',
        '+299',
        '+590',
        '+502',
        '+224',
        '+245',
        '+595',
        '+509',
        '+379',
        '+504',
        '+852',
        '+354',
        '+964',
        '+353',
        '+972',
        '+962',
        '+254',
        '+686',
        '+850',
        '+965',
        '+996',
        '+856',
        '+371',
        '+961',
        '+266',
        '+231',
        '+218',
        '+423',
        '+370',
        '+352',
        '+853',
        '+389',
        '+261',
        '+265',
        '+960',
        '+223',
        '+356',
        '+692',
        '+596',
        '+222',
        '+230',
        '+262',
        '+691',
        '+373',
        '+377',
        '+976',
        '+382',
        '+212',
        '+258',
        '+264',
        '+674',
        '+977',
        '+599',
        '+687',
        '+505',
        '+227',
        '+234',
        '+683',
        '+968',
        '+680',
        '+970',
        '+507',
        '+675',
        '+872',
        '+351',
        '+974',
        '+250',
        '+290',
        '+508',
        '+685',
        '+378',
        '+239',
        '+966',
        '+221',
        '+381',
        '+248',
        '+232',
        '+421',
        '+386',
        '+677',
        '+252',
        '+211',
        '+249',
        '+597',
        '+268',
        '+963',
        '+886',
        '+992',
        '+255',
        '+670',
        '+228',
        '+690',
        '+676',
        '+216',
        '+993',
        '+688',
        '+256',
        '+380',
        '+971',
        '+598',
        '+998',
        '+678',
        '+681',
        '+967',
        '+260',
        '+263',
        '+93',
        '+54',
        '+61',
        '+43',
        '+32',
        '+55',
        '+56',
        '+86',
        '+57',
        '+53',
        '+45',
        '+20',
        '+33',
        '+49',
        '+30',
        '+44',
        '+36',
        '+91',
        '+62',
        '+98',
        '+39',
        '+81',
        '+77',
        '+82',
        '+60',
        '+52',
        '+95',
        '+31',
        '+64',
        '+47',
        '+92',
        '+51',
        '+63',
        '+48',
        '+40',
        '+65',
        '+27',
        '+34',
        '+94',
        '+46',
        '+41',
        '+66',
        '+90',
        '+58',
        '+84',
        '+1',
        '+7',
    ],
];
